In [ ]:
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

# Input data files are available in the read-only "../input/" directory
# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

In [ ]:
data = pd.read_csv("/kaggle/input/cleaned-csv/insurance_claims.csv")

In [ ]:
data.head()

Missing Values

In [ ]:
null_counts = data.isnull().sum()
null_counts

In [ ]:
data_new = data.drop("_c39", axis = 1)

In [ ]:
data_new.head()

Binding Numeric Data

In [ ]:
data_new.describe()

In [ ]:
# Choose the column for the histogram
column_name = 'age'

# Plot the histogram
plt.hist(data[column_name], bins=3, edgecolor='black')

# Add labels and title
plt.xlabel(column_name)
plt.ylabel('Frequency')
plt.title(f'Histogram of {column_name}')

# Display the histogram
plt.show()

In [ ]:
data_new.info()

In [ ]:
bin_edges = [0, 30, 55, 100]  # Define the bin edges
bin_labels = ['Young Adult', 'Middle Aged', 'Elderly']  # Corresponding labels for each bin

# Create a new column based on the bin labels
data_new['ages_category'] = pd.cut(data_new['age'], bins=bin_edges, labels=bin_labels)

In [ ]:
data_new.head()

In [38]:
bin_edges_customer = [0, 25, 150, 500]  # Define the bin edges
bin_labels_customer = ['New Client', 'Established Client', 'Long-Term Client']  # Corresponding labels for each bin

# Create a new column based on the bin labels
data_new['customer_category'] = pd.cut(data_new['months_as_customer'], bins=bin_edges_customer, labels=bin_labels_customer)

In [39]:
data_new.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,ages_category,customer_category
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,71610,6510,13020,52080,Saab,92x,2004,Y,Middle Aged,Long-Term Client
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,5070,780,780,3510,Mercedes,E400,2007,Y,Middle Aged,Long-Term Client
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,34650,7700,3850,23100,Dodge,RAM,2007,N,Young Adult,Established Client
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,Middle Aged,Long-Term Client
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,6500,1300,650,4550,Accura,RSX,2009,N,Middle Aged,Long-Term Client

Creating New Features

In [40]:
data_new["Contract Years"] = data_new["months_as_customer"]/12

In [41]:
data_new.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,ages_category,customer_category,Contract Years
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,6510,13020,52080,Saab,92x,2004,Y,Middle Aged,Long-Term Client,27.333333
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,780,780,3510,Mercedes,E400,2007,Y,Middle Aged,Long-Term Client,19.000000
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,7700,3850,23100,Dodge,RAM,2007,N,Young Adult,Established Client,11.166667
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,6340,6340,50720,Chevrolet,Tahoe,2014,Y,Middle Aged,Long-Term Client,21.333333
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,1300,650,4550,Accura,RSX,2009,N,Middle Aged,Long-Term Client,19.000000

Feature Joining

In [42]:
data_new['total_premiums_paid'] = (data_new['policy_annual_premium']/12) * data_new['months_as_customer']

In [43]:
data_new.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,ages_category,customer_category,Contract Years,total_premiums_paid
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,13020,52080,Saab,92x,2004,Y,Middle Aged,Long-Term Client,27.333333,38455.540000
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,780,3510,Mercedes,E400,2007,Y,Middle Aged,Long-Term Client,19.000000,22747.180000
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,3850,23100,Dodge,RAM,2007,N,Young Adult,Established Client,11.166667,15780.063333
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,6340,50720,Chevrolet,Tahoe,2014,Y,Middle Aged,Long-Term Client,21.333333,30202.453333
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,650,4550,Accura,RSX,2009,N,Middle Aged,Long-Term Client,19.000000,30094.290000

In [44]:
data_new['net_value_of_customer'] = data_new['total_premiums_paid'] - data_new['total_claim_amount']

In [45]:
data_new.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,ages_category,customer_category,Contract Years,total_premiums_paid,net_value_of_customer
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,52080,Saab,92x,2004,Y,Middle Aged,Long-Term Client,27.333333,38455.540000,-33154.460000
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,3510,Mercedes,E400,2007,Y,Middle Aged,Long-Term Client,19.000000,22747.180000,17677.180000
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,23100,Dodge,RAM,2007,N,Young Adult,Established Client,11.166667,15780.063333,-18869.936667
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,50720,Chevrolet,Tahoe,2014,Y,Middle Aged,Long-Term Client,21.333333,30202.453333,-33197.546667
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,4550,Accura,RSX,2009,N,Middle Aged,Long-Term Client,19.000000,30094.290000,23594.290000

Saving the csv for late

In [46]:
data_new.to_csv('Advanced Features Claims Data.csv')

Go wild

In [47]:
data_new.info

<bound method DataFrame.info of      months_as_customer  age  policy_number policy_bind_date policy_state  \
0                   328   48         521585       2014-10-17           OH
1                   228   42         342868       2006-06-27           IN
2                   134   29         687698       2000-09-06           OH
3                   256   41         227811       1990-05-25           IL
4                   228   44         367455       2014-06-06           IL
..                  ...  ...            ...              ...          ...
995                   3   38         941851       1991-07-16           OH
996                 285   41         186934       2014-01-05           IL
997                 130   34         918516       2003-02-17           OH
998                 458   62         533940       2011-11-18           IL
999                 456   60         556080       1996-11-11           OH

    policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  \
0      250/500               1000                1406.91               0
1      250/500               2000                1197.22         5000000
2      100/300               2000                1413.14         5000000
3      250/500               2000                1415.74         6000000
4     500/1000               1000                1583.91         6000000
..         ...                ...                    ...             ...
995   500/1000               1000                1310.80               0
996    100/300               1000                1436.79               0
997    250/500                500                1383.49         3000000
998   500/1000               2000                1356.92         5000000
999    250/500               1000                 766.19               0

     insured_zip  ... vehicle_claim   auto_make auto_model auto_year  \
0         466132  ...         52080        Saab        92x      2004
1         468176  ...          3510    Mercedes       E400      2007
2         430632  ...         23100       Dodge        RAM      2007
3         608117  ...         50720   Chevrolet      Tahoe      2014
4         610706  ...          4550      Accura        RSX      2009
..           ...  ...           ...         ...        ...       ...
995       431289  ...         61040       Honda     Accord      2006
996       608177  ...         72320  Volkswagen     Passat      2015
997       442797  ...         52500      Suburu    Impreza      1996
998       441714  ...         36540        Audi         A5      1998
999       612260  ...          3680    Mercedes       E400      2007

    fraud_reported  ages_category   customer_category Contract Years  \
0                Y    Middle Aged    Long-Term Client      27.333333
1                Y    Middle Aged    Long-Term Client      19.000000
2                N    Young Adult  Established Client      11.166667
3                Y    Middle Aged    Long-Term Client      21.333333
4                N    Middle Aged    Long-Term Client      19.000000
..             ...            ...                 ...            ...
995              N    Middle Aged          New Client       0.250000
996              N    Middle Aged    Long-Term Client      23.750000
997              N    Middle Aged  Established Client      10.833333
998              N        Elderly    Long-Term Client      38.166667
999              N        Elderly    Long-Term Client      38.000000

    total_premiums_paid net_value_of_customer
0          38455.540000         -33154.460000
1          22747.180000          17677.180000
2          15780.063333         -18869.936667
3          30202.453333         -33197.546667
4          30094.290000          23594.290000
..                  ...                   ...
995          327.700000         -86872.300000
996        34123.762500         -74356.237500
997        14987.808333         -52512.191667
998        51789.113333           4809.113333
999        29115.220000          24055.220000

[1000 rows x 44 columns]>